language: node_js
services:
  - postgresql
node_js:
  - "4.2"
before_script:
  - psql -c 'create database stickyboard_ci;' -U postgres
script: 
  - (cd server; NODE_ENV=ci ./node_modules/.bin/knex migrate:latest); NODE_ENV=ci npm test  